=== AlexeyZatsepin/EPAMCoursesProject3/res/diamondFundSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="gems" type="diamondFundType"/>
    <xs:complexType name="diamondFundType">
        <xs:sequence>
            <xs:element name="gemstone" type="gemstone" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="gemstone">
        <xs:sequence>
            <xs:element name = "name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z ]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name = "preciosness" type="preciosnessType"/>
            <xs:element name="origin">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z ]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="visualParameters" type="visualParameters"/>
            <xs:element name = "value" type="xs:positiveInteger"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:simpleType name="preciosnessType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PRECIOUS"/>
            <xs:enumeration value="SEMIPRECIOUS"/>
            <xs:enumeration value="COMMON"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="visualParameters">
        <xs:sequence>
            <xs:element name="color" type="color"/>
            <xs:element name = "transparency">
                <xs:simpleType>
                    <xs:restriction base="xs:float">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name = "verges">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="4"/>
                        <xs:maxInclusive value="15"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="color">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RED"/>
            <xs:enumeration value="BLUE"/>
            <xs:enumeration value="GREEN"/>
            <xs:enumeration value="BLACK"/>
            <xs:enumeration value="ORANGE"/>
            <xs:enumeration value="WHITE"/>
            <xs:enumeration value="YELLOW"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== AlexeyZatsepin/EPAMCoursesProject3/res/result.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="diamondFundSchema.xsd"><gemstone id="TT-10"><name>Yantar</name><preciosness>COMMON</preciosness><origin>Kiev</origin><visualParameters><color>RED</color><transparency>0.5</transparency><verges>6</verges></visualParameters><value>10</value></gemstone></gems>

=== AlexeyZatsepin/EPAMCoursesProject3/res/diamondFund.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="diamondFundSchema.xsd"><gemstone id="TT-12"><name>Diamond</name><preciosness>PRECIOUS</preciosness><origin>Kiev</origin><visualParameters><color>RED</color><transparency>0.4</transparency><verges>4</verges></visualParameters><value>4</value></gemstone><gemstone id="TT-15"><name>Topaz</name><preciosness>SEMIPRECIOUS</preciosness><origin>Lviv</origin><visualParameters><color>BLUE</color><transparency>0.6</transparency><verges>10</verges></visualParameters><value>5</value></gemstone></gems>
